### ISSUE TITLE
Module and lineno in logger are from log-with-context instead of original calling module

### ISSUE THREAD

**Issue by philipcristiano** [neocrym/log-with-context#1]
When using this library with json-log-formatter's `VerboseJSONFormatter` to include more logging information such as the calling module and line number it is this libraries module and lineno included. 

The resulting log includes:

```
"filename": "log_with_context.py", "funcName": "_msg", "levelname": "INFO", "lineno": 78, "module": "log_with_context",
```

**Comment by jamesmishra** [comment]
Thank you for reporting this issue. I just pushed a fix. Try installing log-with-context `0.2.1` and let me know if it works.

If it does not work, feel free to reopen this issue.

Note that if you have any wrapper functions around your `logging.Logger` `debug/info/warn` messages, you will need to adjust the `stacklevel` parameter to a value greater than `1`.

**Comment by philipcristiano** [comment]
Thanks for the quick fix! I've deployed the new version and it's correctly reporting the information!
