### ISSUE TITLE
Question: Is this async compatible?

### ISSUE THREAD

**Issue by cableray** [neocrym/log-with-context#5]
The documentation mentions thread local, but that may not be enough for something like `asyncio`. Async contexts may need special handling. Is that the case, of is that handled by this library? if so, be nice to see that in the docs. Thanks!

**Comment by jamesmishra** [comment]
You bring up a good point. We should assume that log-with-context wouldn't work with asyncio.

**Comment by haritamar** [comment]
Hi @jamesmishra !
I wonder regarding this issue - would using [contextvars](https://docs.python.org/3.7/library/contextvars.html) instead of thread-local storage make this asyncio-compatible?
WDYT?
